version: "3"

services:
  app:
    build: .
    tty: true
    stdin_open: true
    platform: linux/x86_64
    command: npm start
    restart: always
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - .:/app